/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.sosModeling.archModeling.hSFDSL.AElementsBehaviorRoutines;
import org.xtext.sosModeling.archModeling.hSFDSL.AbsArchDecl;
import org.xtext.sosModeling.archModeling.hSFDSL.CSDecl;
import org.xtext.sosModeling.archModeling.hSFDSL.GlobalProperties;
import org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage;
import org.xtext.sosModeling.archModeling.hSFDSL.MedDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abs Arch Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AbsArchDeclImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AbsArchDeclImpl#getMediators <em>Mediators</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AbsArchDeclImpl#getConstitients <em>Constitients</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AbsArchDeclImpl#getAbstractCoaltion <em>Abstract Coaltion</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AbsArchDeclImpl#getGlobalProps <em>Global Props</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AbsArchDeclImpl extends MinimalEObjectImpl.Container implements AbsArchDecl
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getMediators() <em>Mediators</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMediators()
   * @generated
   * @ordered
   */
  protected EList<MedDecl> mediators;

  /**
   * The cached value of the '{@link #getConstitients() <em>Constitients</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstitients()
   * @generated
   * @ordered
   */
  protected EList<CSDecl> constitients;

  /**
   * The cached value of the '{@link #getAbstractCoaltion() <em>Abstract Coaltion</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbstractCoaltion()
   * @generated
   * @ordered
   */
  protected EList<AElementsBehaviorRoutines> abstractCoaltion;

  /**
   * The cached value of the '{@link #getGlobalProps() <em>Global Props</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGlobalProps()
   * @generated
   * @ordered
   */
  protected EList<GlobalProperties> globalProps;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbsArchDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HSFDSLPackage.Literals.ABS_ARCH_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.ABS_ARCH_DECL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MedDecl> getMediators()
  {
    if (mediators == null)
    {
      mediators = new EObjectContainmentEList<MedDecl>(MedDecl.class, this, HSFDSLPackage.ABS_ARCH_DECL__MEDIATORS);
    }
    return mediators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CSDecl> getConstitients()
  {
    if (constitients == null)
    {
      constitients = new EObjectContainmentEList<CSDecl>(CSDecl.class, this, HSFDSLPackage.ABS_ARCH_DECL__CONSTITIENTS);
    }
    return constitients;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AElementsBehaviorRoutines> getAbstractCoaltion()
  {
    if (abstractCoaltion == null)
    {
      abstractCoaltion = new EObjectContainmentEList<AElementsBehaviorRoutines>(AElementsBehaviorRoutines.class, this, HSFDSLPackage.ABS_ARCH_DECL__ABSTRACT_COALTION);
    }
    return abstractCoaltion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<GlobalProperties> getGlobalProps()
  {
    if (globalProps == null)
    {
      globalProps = new EObjectContainmentEList<GlobalProperties>(GlobalProperties.class, this, HSFDSLPackage.ABS_ARCH_DECL__GLOBAL_PROPS);
    }
    return globalProps;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HSFDSLPackage.ABS_ARCH_DECL__MEDIATORS:
        return ((InternalEList<?>)getMediators()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.ABS_ARCH_DECL__CONSTITIENTS:
        return ((InternalEList<?>)getConstitients()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.ABS_ARCH_DECL__ABSTRACT_COALTION:
        return ((InternalEList<?>)getAbstractCoaltion()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.ABS_ARCH_DECL__GLOBAL_PROPS:
        return ((InternalEList<?>)getGlobalProps()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HSFDSLPackage.ABS_ARCH_DECL__NAME:
        return getName();
      case HSFDSLPackage.ABS_ARCH_DECL__MEDIATORS:
        return getMediators();
      case HSFDSLPackage.ABS_ARCH_DECL__CONSTITIENTS:
        return getConstitients();
      case HSFDSLPackage.ABS_ARCH_DECL__ABSTRACT_COALTION:
        return getAbstractCoaltion();
      case HSFDSLPackage.ABS_ARCH_DECL__GLOBAL_PROPS:
        return getGlobalProps();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HSFDSLPackage.ABS_ARCH_DECL__NAME:
        setName((String)newValue);
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__MEDIATORS:
        getMediators().clear();
        getMediators().addAll((Collection<? extends MedDecl>)newValue);
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__CONSTITIENTS:
        getConstitients().clear();
        getConstitients().addAll((Collection<? extends CSDecl>)newValue);
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__ABSTRACT_COALTION:
        getAbstractCoaltion().clear();
        getAbstractCoaltion().addAll((Collection<? extends AElementsBehaviorRoutines>)newValue);
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__GLOBAL_PROPS:
        getGlobalProps().clear();
        getGlobalProps().addAll((Collection<? extends GlobalProperties>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.ABS_ARCH_DECL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__MEDIATORS:
        getMediators().clear();
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__CONSTITIENTS:
        getConstitients().clear();
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__ABSTRACT_COALTION:
        getAbstractCoaltion().clear();
        return;
      case HSFDSLPackage.ABS_ARCH_DECL__GLOBAL_PROPS:
        getGlobalProps().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.ABS_ARCH_DECL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case HSFDSLPackage.ABS_ARCH_DECL__MEDIATORS:
        return mediators != null && !mediators.isEmpty();
      case HSFDSLPackage.ABS_ARCH_DECL__CONSTITIENTS:
        return constitients != null && !constitients.isEmpty();
      case HSFDSLPackage.ABS_ARCH_DECL__ABSTRACT_COALTION:
        return abstractCoaltion != null && !abstractCoaltion.isEmpty();
      case HSFDSLPackage.ABS_ARCH_DECL__GLOBAL_PROPS:
        return globalProps != null && !globalProps.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //AbsArchDeclImpl
