/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.sosModeling.archModeling.hSFDSL.AElementsBehaviorRoutines;
import org.xtext.sosModeling.archModeling.hSFDSL.AddAElements;
import org.xtext.sosModeling.archModeling.hSFDSL.BindElements;
import org.xtext.sosModeling.archModeling.hSFDSL.CColActions;
import org.xtext.sosModeling.archModeling.hSFDSL.ControlDecisions;
import org.xtext.sosModeling.archModeling.hSFDSL.ExponentialRates;
import org.xtext.sosModeling.archModeling.hSFDSL.Expression;
import org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage;
import org.xtext.sosModeling.archModeling.hSFDSL.attachCSs;
import org.xtext.sosModeling.archModeling.hSFDSL.detachCSs;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>AElements Behavior Routines</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getCollaborativeActions <em>Collaborative Actions</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getCaolitionBinding <em>Caolition Binding</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getRemoveElements <em>Remove Elements</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getConnectElenents <em>Connect Elenents</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getControlDecisions <em>Control Decisions</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getActionReates <em>Action Reates</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getAddElements <em>Add Elements</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.AElementsBehaviorRoutinesImpl#getHSFtypes <em>HS Ftypes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AElementsBehaviorRoutinesImpl extends MinimalEObjectImpl.Container implements AElementsBehaviorRoutines
{
  /**
   * The cached value of the '{@link #getCollaborativeActions() <em>Collaborative Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCollaborativeActions()
   * @generated
   * @ordered
   */
  protected EList<CColActions> collaborativeActions;

  /**
   * The cached value of the '{@link #getCaolitionBinding() <em>Caolition Binding</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCaolitionBinding()
   * @generated
   * @ordered
   */
  protected EList<attachCSs> caolitionBinding;

  /**
   * The cached value of the '{@link #getRemoveElements() <em>Remove Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRemoveElements()
   * @generated
   * @ordered
   */
  protected EList<detachCSs> removeElements;

  /**
   * The cached value of the '{@link #getConnectElenents() <em>Connect Elenents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnectElenents()
   * @generated
   * @ordered
   */
  protected EList<BindElements> connectElenents;

  /**
   * The cached value of the '{@link #getControlDecisions() <em>Control Decisions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getControlDecisions()
   * @generated
   * @ordered
   */
  protected EList<ControlDecisions> controlDecisions;

  /**
   * The cached value of the '{@link #getActionReates() <em>Action Reates</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActionReates()
   * @generated
   * @ordered
   */
  protected EList<ExponentialRates> actionReates;

  /**
   * The cached value of the '{@link #getAddElements() <em>Add Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddElements()
   * @generated
   * @ordered
   */
  protected EList<AddAElements> addElements;

  /**
   * The cached value of the '{@link #getHSFtypes() <em>HS Ftypes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHSFtypes()
   * @generated
   * @ordered
   */
  protected Expression hsFtypes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AElementsBehaviorRoutinesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HSFDSLPackage.Literals.AELEMENTS_BEHAVIOR_ROUTINES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CColActions> getCollaborativeActions()
  {
    if (collaborativeActions == null)
    {
      collaborativeActions = new EObjectContainmentEList<CColActions>(CColActions.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS);
    }
    return collaborativeActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<attachCSs> getCaolitionBinding()
  {
    if (caolitionBinding == null)
    {
      caolitionBinding = new EObjectContainmentEList<attachCSs>(attachCSs.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING);
    }
    return caolitionBinding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<detachCSs> getRemoveElements()
  {
    if (removeElements == null)
    {
      removeElements = new EObjectContainmentEList<detachCSs>(detachCSs.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS);
    }
    return removeElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<BindElements> getConnectElenents()
  {
    if (connectElenents == null)
    {
      connectElenents = new EObjectContainmentEList<BindElements>(BindElements.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS);
    }
    return connectElenents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ControlDecisions> getControlDecisions()
  {
    if (controlDecisions == null)
    {
      controlDecisions = new EObjectContainmentEList<ControlDecisions>(ControlDecisions.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS);
    }
    return controlDecisions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExponentialRates> getActionReates()
  {
    if (actionReates == null)
    {
      actionReates = new EObjectContainmentEList<ExponentialRates>(ExponentialRates.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES);
    }
    return actionReates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AddAElements> getAddElements()
  {
    if (addElements == null)
    {
      addElements = new EObjectContainmentEList<AddAElements>(AddAElements.class, this, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS);
    }
    return addElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getHSFtypes()
  {
    return hsFtypes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHSFtypes(Expression newHSFtypes, NotificationChain msgs)
  {
    Expression oldHSFtypes = hsFtypes;
    hsFtypes = newHSFtypes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES, oldHSFtypes, newHSFtypes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHSFtypes(Expression newHSFtypes)
  {
    if (newHSFtypes != hsFtypes)
    {
      NotificationChain msgs = null;
      if (hsFtypes != null)
        msgs = ((InternalEObject)hsFtypes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES, null, msgs);
      if (newHSFtypes != null)
        msgs = ((InternalEObject)newHSFtypes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES, null, msgs);
      msgs = basicSetHSFtypes(newHSFtypes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES, newHSFtypes, newHSFtypes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS:
        return ((InternalEList<?>)getCollaborativeActions()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING:
        return ((InternalEList<?>)getCaolitionBinding()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS:
        return ((InternalEList<?>)getRemoveElements()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS:
        return ((InternalEList<?>)getConnectElenents()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS:
        return ((InternalEList<?>)getControlDecisions()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES:
        return ((InternalEList<?>)getActionReates()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS:
        return ((InternalEList<?>)getAddElements()).basicRemove(otherEnd, msgs);
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES:
        return basicSetHSFtypes(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS:
        return getCollaborativeActions();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING:
        return getCaolitionBinding();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS:
        return getRemoveElements();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS:
        return getConnectElenents();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS:
        return getControlDecisions();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES:
        return getActionReates();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS:
        return getAddElements();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES:
        return getHSFtypes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS:
        getCollaborativeActions().clear();
        getCollaborativeActions().addAll((Collection<? extends CColActions>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING:
        getCaolitionBinding().clear();
        getCaolitionBinding().addAll((Collection<? extends attachCSs>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS:
        getRemoveElements().clear();
        getRemoveElements().addAll((Collection<? extends detachCSs>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS:
        getConnectElenents().clear();
        getConnectElenents().addAll((Collection<? extends BindElements>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS:
        getControlDecisions().clear();
        getControlDecisions().addAll((Collection<? extends ControlDecisions>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES:
        getActionReates().clear();
        getActionReates().addAll((Collection<? extends ExponentialRates>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS:
        getAddElements().clear();
        getAddElements().addAll((Collection<? extends AddAElements>)newValue);
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES:
        setHSFtypes((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS:
        getCollaborativeActions().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING:
        getCaolitionBinding().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS:
        getRemoveElements().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS:
        getConnectElenents().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS:
        getControlDecisions().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES:
        getActionReates().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS:
        getAddElements().clear();
        return;
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES:
        setHSFtypes((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS:
        return collaborativeActions != null && !collaborativeActions.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING:
        return caolitionBinding != null && !caolitionBinding.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS:
        return removeElements != null && !removeElements.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS:
        return connectElenents != null && !connectElenents.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS:
        return controlDecisions != null && !controlDecisions.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES:
        return actionReates != null && !actionReates.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS:
        return addElements != null && !addElements.isEmpty();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES:
        return hsFtypes != null;
    }
    return super.eIsSet(featureID);
  }

} //AElementsBehaviorRoutinesImpl
