/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.sosModeling.archModeling.hSFDSL.DefineMediationRoles;
import org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage;
import org.xtext.sosModeling.archModeling.hSFDSL.publicinterfaeceDef;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Define Mediation Roles</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.DefineMediationRolesImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.DefineMediationRolesImpl#getPubliicIntractionpointare <em>Publiic Intractionpointare</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.DefineMediationRolesImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefineMediationRolesImpl extends MinimalEObjectImpl.Container implements DefineMediationRoles
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getPubliicIntractionpointare() <em>Publiic Intractionpointare</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPubliicIntractionpointare()
   * @generated
   * @ordered
   */
  protected EList<publicinterfaeceDef> publiicIntractionpointare;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefineMediationRolesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HSFDSLPackage.Literals.DEFINE_MEDIATION_ROLES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.DEFINE_MEDIATION_ROLES__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<publicinterfaeceDef> getPubliicIntractionpointare()
  {
    if (publiicIntractionpointare == null)
    {
      publiicIntractionpointare = new EObjectResolvingEList<publicinterfaeceDef>(publicinterfaeceDef.class, this, HSFDSLPackage.DEFINE_MEDIATION_ROLES__PUBLIIC_INTRACTIONPOINTARE);
    }
    return publiicIntractionpointare;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.DEFINE_MEDIATION_ROLES__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__TYPE:
        return getType();
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__PUBLIIC_INTRACTIONPOINTARE:
        return getPubliicIntractionpointare();
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__TYPE:
        setType((String)newValue);
        return;
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__PUBLIIC_INTRACTIONPOINTARE:
        getPubliicIntractionpointare().clear();
        getPubliicIntractionpointare().addAll((Collection<? extends publicinterfaeceDef>)newValue);
        return;
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__PUBLIIC_INTRACTIONPOINTARE:
        getPubliicIntractionpointare().clear();
        return;
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__PUBLIIC_INTRACTIONPOINTARE:
        return publiicIntractionpointare != null && !publiicIntractionpointare.isEmpty();
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //DefineMediationRolesImpl
