/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.sosModeling.archModeling.hSFDSL.GlobalProperties;
import org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage;
import org.xtext.sosModeling.archModeling.hSFDSL.initVals;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Global Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.GlobalPropertiesImpl#getPropertyType <em>Property Type</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.GlobalPropertiesImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.impl.GlobalPropertiesImpl#getAttrinit <em>Attrinit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GlobalPropertiesImpl extends MinimalEObjectImpl.Container implements GlobalProperties
{
  /**
   * The default value of the '{@link #getPropertyType() <em>Property Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPropertyType()
   * @generated
   * @ordered
   */
  protected static final String PROPERTY_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPropertyType() <em>Property Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPropertyType()
   * @generated
   * @ordered
   */
  protected String propertyType = PROPERTY_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttrinit() <em>Attrinit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttrinit()
   * @generated
   * @ordered
   */
  protected initVals attrinit;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GlobalPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HSFDSLPackage.Literals.GLOBAL_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPropertyType()
  {
    return propertyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPropertyType(String newPropertyType)
  {
    String oldPropertyType = propertyType;
    propertyType = newPropertyType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.GLOBAL_PROPERTIES__PROPERTY_TYPE, oldPropertyType, propertyType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.GLOBAL_PROPERTIES__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public initVals getAttrinit()
  {
    return attrinit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttrinit(initVals newAttrinit, NotificationChain msgs)
  {
    initVals oldAttrinit = attrinit;
    attrinit = newAttrinit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT, oldAttrinit, newAttrinit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttrinit(initVals newAttrinit)
  {
    if (newAttrinit != attrinit)
    {
      NotificationChain msgs = null;
      if (attrinit != null)
        msgs = ((InternalEObject)attrinit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT, null, msgs);
      if (newAttrinit != null)
        msgs = ((InternalEObject)newAttrinit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT, null, msgs);
      msgs = basicSetAttrinit(newAttrinit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT, newAttrinit, newAttrinit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT:
        return basicSetAttrinit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HSFDSLPackage.GLOBAL_PROPERTIES__PROPERTY_TYPE:
        return getPropertyType();
      case HSFDSLPackage.GLOBAL_PROPERTIES__NAME:
        return getName();
      case HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT:
        return getAttrinit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HSFDSLPackage.GLOBAL_PROPERTIES__PROPERTY_TYPE:
        setPropertyType((String)newValue);
        return;
      case HSFDSLPackage.GLOBAL_PROPERTIES__NAME:
        setName((String)newValue);
        return;
      case HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT:
        setAttrinit((initVals)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.GLOBAL_PROPERTIES__PROPERTY_TYPE:
        setPropertyType(PROPERTY_TYPE_EDEFAULT);
        return;
      case HSFDSLPackage.GLOBAL_PROPERTIES__NAME:
        setName(NAME_EDEFAULT);
        return;
      case HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT:
        setAttrinit((initVals)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HSFDSLPackage.GLOBAL_PROPERTIES__PROPERTY_TYPE:
        return PROPERTY_TYPE_EDEFAULT == null ? propertyType != null : !PROPERTY_TYPE_EDEFAULT.equals(propertyType);
      case HSFDSLPackage.GLOBAL_PROPERTIES__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case HSFDSLPackage.GLOBAL_PROPERTIES__ATTRINIT:
        return attrinit != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (PropertyType: ");
    result.append(propertyType);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //GlobalPropertiesImpl
