/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.sosModeling.archModeling.hSFDSL.AElementsBehaviorRoutines;
import org.xtext.sosModeling.archModeling.hSFDSL.AbsArchDecl;
import org.xtext.sosModeling.archModeling.hSFDSL.AddAElements;
import org.xtext.sosModeling.archModeling.hSFDSL.Askopeator;
import org.xtext.sosModeling.archModeling.hSFDSL.BindElements;
import org.xtext.sosModeling.archModeling.hSFDSL.BooleanLiteral;
import org.xtext.sosModeling.archModeling.hSFDSL.CColActions;
import org.xtext.sosModeling.archModeling.hSFDSL.CConsDecl;
import org.xtext.sosModeling.archModeling.hSFDSL.CSDecl;
import org.xtext.sosModeling.archModeling.hSFDSL.CSMembersDefintion;
import org.xtext.sosModeling.archModeling.hSFDSL.ControlDecisions;
import org.xtext.sosModeling.archModeling.hSFDSL.DefineMediationRoles;
import org.xtext.sosModeling.archModeling.hSFDSL.EqualityExpression;
import org.xtext.sosModeling.archModeling.hSFDSL.ExponentialRates;
import org.xtext.sosModeling.archModeling.hSFDSL.Expression;
import org.xtext.sosModeling.archModeling.hSFDSL.GlobalProperties;
import org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLFactory;
import org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage;
import org.xtext.sosModeling.archModeling.hSFDSL.IntegerLiteral;
import org.xtext.sosModeling.archModeling.hSFDSL.LogicalExpression;
import org.xtext.sosModeling.archModeling.hSFDSL.MedDecl;
import org.xtext.sosModeling.archModeling.hSFDSL.MedRoleDeclaration;
import org.xtext.sosModeling.archModeling.hSFDSL.MinusOperation;
import org.xtext.sosModeling.archModeling.hSFDSL.ModelElementsDecaration;
import org.xtext.sosModeling.archModeling.hSFDSL.NegationExpression;
import org.xtext.sosModeling.archModeling.hSFDSL.ProtDeclaration;
import org.xtext.sosModeling.archModeling.hSFDSL.RealLiteral;
import org.xtext.sosModeling.archModeling.hSFDSL.RelationalExpression;
import org.xtext.sosModeling.archModeling.hSFDSL.StochasticModeling;
import org.xtext.sosModeling.archModeling.hSFDSL.StochsticBehaviors;
import org.xtext.sosModeling.archModeling.hSFDSL.StringLiteral;
import org.xtext.sosModeling.archModeling.hSFDSL.SumOperation;
import org.xtext.sosModeling.archModeling.hSFDSL.Telloperator;
import org.xtext.sosModeling.archModeling.hSFDSL.Term;
import org.xtext.sosModeling.archModeling.hSFDSL.VariableRef;
import org.xtext.sosModeling.archModeling.hSFDSL.attachCSs;
import org.xtext.sosModeling.archModeling.hSFDSL.detachCSs;
import org.xtext.sosModeling.archModeling.hSFDSL.formalParameter;
import org.xtext.sosModeling.archModeling.hSFDSL.formalParameterList;
import org.xtext.sosModeling.archModeling.hSFDSL.formalParameters;
import org.xtext.sosModeling.archModeling.hSFDSL.functinality;
import org.xtext.sosModeling.archModeling.hSFDSL.initVals;
import org.xtext.sosModeling.archModeling.hSFDSL.publicinterfaeceDef;
import org.xtext.sosModeling.archModeling.hSFDSL.traitDeclaration;
import org.xtext.sosModeling.archModeling.hSFDSL.variableDeclaratorId;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HSFDSLPackageImpl extends EPackageImpl implements HSFDSLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stochasticModelingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelElementsDecarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass csDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass csMembersDefintionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stochsticBehaviorsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass publicinterfaeceDefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass formalParametersEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass formalParameterListEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass formalParameterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variableDeclaratorIdEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass protDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass aElementsBehaviorRoutinesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cColActionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass functinalityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass addAElementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass attachCSsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass detachCSsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass bindElementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass controlDecisionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exponentialRatesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cConsDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass telloperatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass askopeatorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass traitDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass medDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass medRoleDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass defineMediationRolesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass absArchDeclEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass globalPropertiesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initValsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass floatEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass logicalExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass equalityExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass relationalExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sumOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass minusOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass termEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass negationExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variableRefEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integerLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass booleanLiteralEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private HSFDSLPackageImpl()
  {
    super(eNS_URI, HSFDSLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link HSFDSLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static HSFDSLPackage init()
  {
    if (isInited) return (HSFDSLPackage)EPackage.Registry.INSTANCE.getEPackage(HSFDSLPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredHSFDSLPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    HSFDSLPackageImpl theHSFDSLPackage = registeredHSFDSLPackage instanceof HSFDSLPackageImpl ? (HSFDSLPackageImpl)registeredHSFDSLPackage : new HSFDSLPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theHSFDSLPackage.createPackageContents();

    // Initialize created meta-data
    theHSFDSLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theHSFDSLPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(HSFDSLPackage.eNS_URI, theHSFDSLPackage);
    return theHSFDSLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStochasticModeling()
  {
    return stochasticModelingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStochasticModeling_StochasticModelElements()
  {
    return (EReference)stochasticModelingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModelElementsDecaration()
  {
    return modelElementsDecarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_AbstractArchModel()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_ConstiuenetSystemSDesign()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_MediatorDesign()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_ConcurrentConstraints()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_ArchitecutreElementsBehaviors()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModelElementsDecaration_Name()
  {
    return (EAttribute)modelElementsDecarationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_Interfce()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModelElementsDecaration_ArchTraits()
  {
    return (EReference)modelElementsDecarationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCSDecl()
  {
    return csDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCSDecl_Name()
  {
    return (EAttribute)csDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCSDecl_CSDesignConsists()
  {
    return (EReference)csDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCSMembersDefintion()
  {
    return csMembersDefintionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCSMembersDefintion_Ports()
  {
    return (EReference)csMembersDefintionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCSMembersDefintion_AActions()
  {
    return (EReference)csMembersDefintionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCSMembersDefintion_CSConConstraints()
  {
    return (EReference)csMembersDefintionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCSMembersDefintion_CSCoreBehavior()
  {
    return (EReference)csMembersDefintionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStochsticBehaviors()
  {
    return stochsticBehaviorsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStochsticBehaviors_Type()
  {
    return (EAttribute)stochsticBehaviorsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStochsticBehaviors_Name()
  {
    return (EAttribute)stochsticBehaviorsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStochsticBehaviors_ParamsDecl()
  {
    return (EReference)stochsticBehaviorsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStochsticBehaviors_Functions()
  {
    return (EReference)stochsticBehaviorsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getpublicinterfaeceDef()
  {
    return publicinterfaeceDefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getpublicinterfaeceDef_Name()
  {
    return (EAttribute)publicinterfaeceDefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getpublicinterfaeceDef_ParamsDecl()
  {
    return (EReference)publicinterfaeceDefEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getformalParameters()
  {
    return formalParametersEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getformalParameters_ParamsDecl()
  {
    return (EReference)formalParametersEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getformalParameterList()
  {
    return formalParameterListEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getformalParameterList_ParamDecl()
  {
    return (EReference)formalParameterListEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getformalParameterList_ParamsDecl()
  {
    return (EReference)formalParameterListEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getformalParameter()
  {
    return formalParameterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getformalParameter_Type()
  {
    return (EAttribute)formalParameterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getformalParameter_Name()
  {
    return (EReference)formalParameterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getvariableDeclaratorId()
  {
    return variableDeclaratorIdEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getvariableDeclaratorId_Name()
  {
    return (EAttribute)variableDeclaratorIdEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getProtDeclaration()
  {
    return protDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProtDeclaration_Porttype()
  {
    return (EAttribute)protDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getProtDeclaration_PubliicIntractionpointare()
  {
    return (EReference)protDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProtDeclaration_Name()
  {
    return (EAttribute)protDeclarationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAElementsBehaviorRoutines()
  {
    return aElementsBehaviorRoutinesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_CollaborativeActions()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_CaolitionBinding()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_RemoveElements()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_ConnectElenents()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_ControlDecisions()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_ActionReates()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_AddElements()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAElementsBehaviorRoutines_HSFtypes()
  {
    return (EReference)aElementsBehaviorRoutinesEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCColActions()
  {
    return cColActionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCColActions_Name()
  {
    return (EAttribute)cColActionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCColActions_Type()
  {
    return (EAttribute)cColActionsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCColActions_ParamsDecl()
  {
    return (EReference)cColActionsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCColActions_MethodBody()
  {
    return (EReference)cColActionsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getfunctinality()
  {
    return functinalityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getfunctinality_Functions()
  {
    return (EReference)functinalityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getfunctinality_Actions()
  {
    return (EReference)functinalityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getfunctinality_Target()
  {
    return (EReference)functinalityEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddAElements()
  {
    return addAElementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddAElements_Name()
  {
    return (EAttribute)addAElementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddAElements_Type()
  {
    return (EAttribute)addAElementsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getattachCSs()
  {
    return attachCSsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getattachCSs_AttachParam1()
  {
    return (EReference)attachCSsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getattachCSs_AttachParam2()
  {
    return (EReference)attachCSsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getdetachCSs()
  {
    return detachCSsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getdetachCSs_DetachParam1()
  {
    return (EReference)detachCSsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getdetachCSs_DetachParam2()
  {
    return (EReference)detachCSsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBindElements()
  {
    return bindElementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBindElements_BindParam1()
  {
    return (EReference)bindElementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getBindElements_BindParam2()
  {
    return (EReference)bindElementsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getControlDecisions()
  {
    return controlDecisionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getControlDecisions_ExpressionDecl()
  {
    return (EReference)controlDecisionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getControlDecisions_StatementDecl1()
  {
    return (EReference)controlDecisionsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getControlDecisions_ExpressionOrDecl()
  {
    return (EReference)controlDecisionsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getControlDecisions_StatementDecl2()
  {
    return (EReference)controlDecisionsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExponentialRates()
  {
    return exponentialRatesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExponentialRates_DelayValue()
  {
    return (EAttribute)exponentialRatesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExponentialRates_ExponentialRates()
  {
    return (EReference)exponentialRatesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCConsDecl()
  {
    return cConsDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCConsDecl_Name()
  {
    return (EAttribute)cConsDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCConsDecl_Askconstraints()
  {
    return (EReference)cConsDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCConsDecl_Tellconstraints()
  {
    return (EReference)cConsDeclEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTelloperator()
  {
    return telloperatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTelloperator_ConstraintShareDate()
  {
    return (EAttribute)telloperatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTelloperator_Rate()
  {
    return (EReference)telloperatorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAskopeator()
  {
    return askopeatorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAskopeator_ConstraintData()
  {
    return (EAttribute)askopeatorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAskopeator_Rate()
  {
    return (EReference)askopeatorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass gettraitDeclaration()
  {
    return traitDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute gettraitDeclaration_Name()
  {
    return (EAttribute)traitDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference gettraitDeclaration_Ports()
  {
    return (EReference)traitDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference gettraitDeclaration_Roles()
  {
    return (EReference)traitDeclarationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMedDecl()
  {
    return medDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMedDecl_Name()
  {
    return (EAttribute)medDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMedDecl_MedRoles()
  {
    return (EReference)medDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMedDecl_AActions()
  {
    return (EReference)medDeclEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMedDecl_CSConConstraints()
  {
    return (EReference)medDeclEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMedDecl_MedCoreBehavior()
  {
    return (EReference)medDeclEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMedRoleDeclaration()
  {
    return medRoleDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMedRoleDeclaration_MediationRoles()
  {
    return (EReference)medRoleDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDefineMediationRoles()
  {
    return defineMediationRolesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefineMediationRoles_Type()
  {
    return (EAttribute)defineMediationRolesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDefineMediationRoles_PubliicIntractionpointare()
  {
    return (EReference)defineMediationRolesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefineMediationRoles_Name()
  {
    return (EAttribute)defineMediationRolesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAbsArchDecl()
  {
    return absArchDeclEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAbsArchDecl_Name()
  {
    return (EAttribute)absArchDeclEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAbsArchDecl_Mediators()
  {
    return (EReference)absArchDeclEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAbsArchDecl_Constitients()
  {
    return (EReference)absArchDeclEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAbsArchDecl_AbstractCoaltion()
  {
    return (EReference)absArchDeclEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAbsArchDecl_GlobalProps()
  {
    return (EReference)absArchDeclEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGlobalProperties()
  {
    return globalPropertiesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalProperties_PropertyType()
  {
    return (EAttribute)globalPropertiesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGlobalProperties_Name()
  {
    return (EAttribute)globalPropertiesEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGlobalProperties_Attrinit()
  {
    return (EReference)globalPropertiesEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getinitVals()
  {
    return initValsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFLOAT()
  {
    return floatEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFLOAT_Value()
  {
    return (EAttribute)floatEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpression()
  {
    return expressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLogicalExpression()
  {
    return logicalExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLogicalExpression_Left()
  {
    return (EReference)logicalExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLogicalExpression_Op()
  {
    return (EAttribute)logicalExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getLogicalExpression_Right()
  {
    return (EReference)logicalExpressionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEqualityExpression()
  {
    return equalityExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEqualityExpression_Left()
  {
    return (EReference)equalityExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEqualityExpression_Op()
  {
    return (EAttribute)equalityExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getEqualityExpression_Right()
  {
    return (EReference)equalityExpressionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRelationalExpression()
  {
    return relationalExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelationalExpression_Left()
  {
    return (EReference)relationalExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRelationalExpression_Op()
  {
    return (EAttribute)relationalExpressionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRelationalExpression_Right()
  {
    return (EReference)relationalExpressionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSumOperation()
  {
    return sumOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSumOperation_Left()
  {
    return (EReference)sumOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSumOperation_Op()
  {
    return (EAttribute)sumOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSumOperation_Right()
  {
    return (EReference)sumOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMinusOperation()
  {
    return minusOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMinusOperation_Left()
  {
    return (EReference)minusOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMinusOperation_Op()
  {
    return (EAttribute)minusOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMinusOperation_Right()
  {
    return (EReference)minusOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTerm()
  {
    return termEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTerm_Left()
  {
    return (EReference)termEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTerm_Op()
  {
    return (EAttribute)termEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getTerm_Right()
  {
    return (EReference)termEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNegationExpression()
  {
    return negationExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNegationExpression_Expression()
  {
    return (EReference)negationExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariableRef()
  {
    return variableRefEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariableRef_Variable()
  {
    return (EAttribute)variableRefEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegerLiteral()
  {
    return integerLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntegerLiteral_Value()
  {
    return (EAttribute)integerLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealLiteral()
  {
    return realLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRealLiteral_Value()
  {
    return (EReference)realLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringLiteral()
  {
    return stringLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStringLiteral_Value()
  {
    return (EAttribute)stringLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBooleanLiteral()
  {
    return booleanLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getBooleanLiteral_Value()
  {
    return (EAttribute)booleanLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HSFDSLFactory getHSFDSLFactory()
  {
    return (HSFDSLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    stochasticModelingEClass = createEClass(STOCHASTIC_MODELING);
    createEReference(stochasticModelingEClass, STOCHASTIC_MODELING__STOCHASTIC_MODEL_ELEMENTS);

    modelElementsDecarationEClass = createEClass(MODEL_ELEMENTS_DECARATION);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__ABSTRACT_ARCH_MODEL);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__CONSTIUENET_SYSTEM_SDESIGN);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__MEDIATOR_DESIGN);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__CONCURRENT_CONSTRAINTS);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__ARCHITECUTRE_ELEMENTS_BEHAVIORS);
    createEAttribute(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__NAME);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__INTERFCE);
    createEReference(modelElementsDecarationEClass, MODEL_ELEMENTS_DECARATION__ARCH_TRAITS);

    csDeclEClass = createEClass(CS_DECL);
    createEAttribute(csDeclEClass, CS_DECL__NAME);
    createEReference(csDeclEClass, CS_DECL__CS_DESIGN_CONSISTS);

    csMembersDefintionEClass = createEClass(CS_MEMBERS_DEFINTION);
    createEReference(csMembersDefintionEClass, CS_MEMBERS_DEFINTION__PORTS);
    createEReference(csMembersDefintionEClass, CS_MEMBERS_DEFINTION__AACTIONS);
    createEReference(csMembersDefintionEClass, CS_MEMBERS_DEFINTION__CS_CON_CONSTRAINTS);
    createEReference(csMembersDefintionEClass, CS_MEMBERS_DEFINTION__CS_CORE_BEHAVIOR);

    stochsticBehaviorsEClass = createEClass(STOCHSTIC_BEHAVIORS);
    createEAttribute(stochsticBehaviorsEClass, STOCHSTIC_BEHAVIORS__TYPE);
    createEAttribute(stochsticBehaviorsEClass, STOCHSTIC_BEHAVIORS__NAME);
    createEReference(stochsticBehaviorsEClass, STOCHSTIC_BEHAVIORS__PARAMS_DECL);
    createEReference(stochsticBehaviorsEClass, STOCHSTIC_BEHAVIORS__FUNCTIONS);

    publicinterfaeceDefEClass = createEClass(PUBLICINTERFAECE_DEF);
    createEAttribute(publicinterfaeceDefEClass, PUBLICINTERFAECE_DEF__NAME);
    createEReference(publicinterfaeceDefEClass, PUBLICINTERFAECE_DEF__PARAMS_DECL);

    formalParametersEClass = createEClass(FORMAL_PARAMETERS);
    createEReference(formalParametersEClass, FORMAL_PARAMETERS__PARAMS_DECL);

    formalParameterListEClass = createEClass(FORMAL_PARAMETER_LIST);
    createEReference(formalParameterListEClass, FORMAL_PARAMETER_LIST__PARAM_DECL);
    createEReference(formalParameterListEClass, FORMAL_PARAMETER_LIST__PARAMS_DECL);

    formalParameterEClass = createEClass(FORMAL_PARAMETER);
    createEAttribute(formalParameterEClass, FORMAL_PARAMETER__TYPE);
    createEReference(formalParameterEClass, FORMAL_PARAMETER__NAME);

    variableDeclaratorIdEClass = createEClass(VARIABLE_DECLARATOR_ID);
    createEAttribute(variableDeclaratorIdEClass, VARIABLE_DECLARATOR_ID__NAME);

    protDeclarationEClass = createEClass(PROT_DECLARATION);
    createEAttribute(protDeclarationEClass, PROT_DECLARATION__PORTTYPE);
    createEReference(protDeclarationEClass, PROT_DECLARATION__PUBLIIC_INTRACTIONPOINTARE);
    createEAttribute(protDeclarationEClass, PROT_DECLARATION__NAME);

    aElementsBehaviorRoutinesEClass = createEClass(AELEMENTS_BEHAVIOR_ROUTINES);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__COLLABORATIVE_ACTIONS);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__CAOLITION_BINDING);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__REMOVE_ELEMENTS);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__CONNECT_ELENENTS);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__CONTROL_DECISIONS);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__ACTION_REATES);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__ADD_ELEMENTS);
    createEReference(aElementsBehaviorRoutinesEClass, AELEMENTS_BEHAVIOR_ROUTINES__HS_FTYPES);

    cColActionsEClass = createEClass(CCOL_ACTIONS);
    createEAttribute(cColActionsEClass, CCOL_ACTIONS__NAME);
    createEAttribute(cColActionsEClass, CCOL_ACTIONS__TYPE);
    createEReference(cColActionsEClass, CCOL_ACTIONS__PARAMS_DECL);
    createEReference(cColActionsEClass, CCOL_ACTIONS__METHOD_BODY);

    functinalityEClass = createEClass(FUNCTINALITY);
    createEReference(functinalityEClass, FUNCTINALITY__FUNCTIONS);
    createEReference(functinalityEClass, FUNCTINALITY__ACTIONS);
    createEReference(functinalityEClass, FUNCTINALITY__TARGET);

    addAElementsEClass = createEClass(ADD_AELEMENTS);
    createEAttribute(addAElementsEClass, ADD_AELEMENTS__NAME);
    createEAttribute(addAElementsEClass, ADD_AELEMENTS__TYPE);

    attachCSsEClass = createEClass(ATTACH_CSS);
    createEReference(attachCSsEClass, ATTACH_CSS__ATTACH_PARAM1);
    createEReference(attachCSsEClass, ATTACH_CSS__ATTACH_PARAM2);

    detachCSsEClass = createEClass(DETACH_CSS);
    createEReference(detachCSsEClass, DETACH_CSS__DETACH_PARAM1);
    createEReference(detachCSsEClass, DETACH_CSS__DETACH_PARAM2);

    bindElementsEClass = createEClass(BIND_ELEMENTS);
    createEReference(bindElementsEClass, BIND_ELEMENTS__BIND_PARAM1);
    createEReference(bindElementsEClass, BIND_ELEMENTS__BIND_PARAM2);

    controlDecisionsEClass = createEClass(CONTROL_DECISIONS);
    createEReference(controlDecisionsEClass, CONTROL_DECISIONS__EXPRESSION_DECL);
    createEReference(controlDecisionsEClass, CONTROL_DECISIONS__STATEMENT_DECL1);
    createEReference(controlDecisionsEClass, CONTROL_DECISIONS__EXPRESSION_OR_DECL);
    createEReference(controlDecisionsEClass, CONTROL_DECISIONS__STATEMENT_DECL2);

    exponentialRatesEClass = createEClass(EXPONENTIAL_RATES);
    createEAttribute(exponentialRatesEClass, EXPONENTIAL_RATES__DELAY_VALUE);
    createEReference(exponentialRatesEClass, EXPONENTIAL_RATES__EXPONENTIAL_RATES);

    cConsDeclEClass = createEClass(CCONS_DECL);
    createEAttribute(cConsDeclEClass, CCONS_DECL__NAME);
    createEReference(cConsDeclEClass, CCONS_DECL__ASKCONSTRAINTS);
    createEReference(cConsDeclEClass, CCONS_DECL__TELLCONSTRAINTS);

    telloperatorEClass = createEClass(TELLOPERATOR);
    createEAttribute(telloperatorEClass, TELLOPERATOR__CONSTRAINT_SHARE_DATE);
    createEReference(telloperatorEClass, TELLOPERATOR__RATE);

    askopeatorEClass = createEClass(ASKOPEATOR);
    createEAttribute(askopeatorEClass, ASKOPEATOR__CONSTRAINT_DATA);
    createEReference(askopeatorEClass, ASKOPEATOR__RATE);

    traitDeclarationEClass = createEClass(TRAIT_DECLARATION);
    createEAttribute(traitDeclarationEClass, TRAIT_DECLARATION__NAME);
    createEReference(traitDeclarationEClass, TRAIT_DECLARATION__PORTS);
    createEReference(traitDeclarationEClass, TRAIT_DECLARATION__ROLES);

    medDeclEClass = createEClass(MED_DECL);
    createEAttribute(medDeclEClass, MED_DECL__NAME);
    createEReference(medDeclEClass, MED_DECL__MED_ROLES);
    createEReference(medDeclEClass, MED_DECL__AACTIONS);
    createEReference(medDeclEClass, MED_DECL__CS_CON_CONSTRAINTS);
    createEReference(medDeclEClass, MED_DECL__MED_CORE_BEHAVIOR);

    medRoleDeclarationEClass = createEClass(MED_ROLE_DECLARATION);
    createEReference(medRoleDeclarationEClass, MED_ROLE_DECLARATION__MEDIATION_ROLES);

    defineMediationRolesEClass = createEClass(DEFINE_MEDIATION_ROLES);
    createEAttribute(defineMediationRolesEClass, DEFINE_MEDIATION_ROLES__TYPE);
    createEReference(defineMediationRolesEClass, DEFINE_MEDIATION_ROLES__PUBLIIC_INTRACTIONPOINTARE);
    createEAttribute(defineMediationRolesEClass, DEFINE_MEDIATION_ROLES__NAME);

    absArchDeclEClass = createEClass(ABS_ARCH_DECL);
    createEAttribute(absArchDeclEClass, ABS_ARCH_DECL__NAME);
    createEReference(absArchDeclEClass, ABS_ARCH_DECL__MEDIATORS);
    createEReference(absArchDeclEClass, ABS_ARCH_DECL__CONSTITIENTS);
    createEReference(absArchDeclEClass, ABS_ARCH_DECL__ABSTRACT_COALTION);
    createEReference(absArchDeclEClass, ABS_ARCH_DECL__GLOBAL_PROPS);

    globalPropertiesEClass = createEClass(GLOBAL_PROPERTIES);
    createEAttribute(globalPropertiesEClass, GLOBAL_PROPERTIES__PROPERTY_TYPE);
    createEAttribute(globalPropertiesEClass, GLOBAL_PROPERTIES__NAME);
    createEReference(globalPropertiesEClass, GLOBAL_PROPERTIES__ATTRINIT);

    initValsEClass = createEClass(INIT_VALS);

    floatEClass = createEClass(FLOAT);
    createEAttribute(floatEClass, FLOAT__VALUE);

    expressionEClass = createEClass(EXPRESSION);

    logicalExpressionEClass = createEClass(LOGICAL_EXPRESSION);
    createEReference(logicalExpressionEClass, LOGICAL_EXPRESSION__LEFT);
    createEAttribute(logicalExpressionEClass, LOGICAL_EXPRESSION__OP);
    createEReference(logicalExpressionEClass, LOGICAL_EXPRESSION__RIGHT);

    equalityExpressionEClass = createEClass(EQUALITY_EXPRESSION);
    createEReference(equalityExpressionEClass, EQUALITY_EXPRESSION__LEFT);
    createEAttribute(equalityExpressionEClass, EQUALITY_EXPRESSION__OP);
    createEReference(equalityExpressionEClass, EQUALITY_EXPRESSION__RIGHT);

    relationalExpressionEClass = createEClass(RELATIONAL_EXPRESSION);
    createEReference(relationalExpressionEClass, RELATIONAL_EXPRESSION__LEFT);
    createEAttribute(relationalExpressionEClass, RELATIONAL_EXPRESSION__OP);
    createEReference(relationalExpressionEClass, RELATIONAL_EXPRESSION__RIGHT);

    sumOperationEClass = createEClass(SUM_OPERATION);
    createEReference(sumOperationEClass, SUM_OPERATION__LEFT);
    createEAttribute(sumOperationEClass, SUM_OPERATION__OP);
    createEReference(sumOperationEClass, SUM_OPERATION__RIGHT);

    minusOperationEClass = createEClass(MINUS_OPERATION);
    createEReference(minusOperationEClass, MINUS_OPERATION__LEFT);
    createEAttribute(minusOperationEClass, MINUS_OPERATION__OP);
    createEReference(minusOperationEClass, MINUS_OPERATION__RIGHT);

    termEClass = createEClass(TERM);
    createEReference(termEClass, TERM__LEFT);
    createEAttribute(termEClass, TERM__OP);
    createEReference(termEClass, TERM__RIGHT);

    negationExpressionEClass = createEClass(NEGATION_EXPRESSION);
    createEReference(negationExpressionEClass, NEGATION_EXPRESSION__EXPRESSION);

    variableRefEClass = createEClass(VARIABLE_REF);
    createEAttribute(variableRefEClass, VARIABLE_REF__VARIABLE);

    integerLiteralEClass = createEClass(INTEGER_LITERAL);
    createEAttribute(integerLiteralEClass, INTEGER_LITERAL__VALUE);

    realLiteralEClass = createEClass(REAL_LITERAL);
    createEReference(realLiteralEClass, REAL_LITERAL__VALUE);

    stringLiteralEClass = createEClass(STRING_LITERAL);
    createEAttribute(stringLiteralEClass, STRING_LITERAL__VALUE);

    booleanLiteralEClass = createEClass(BOOLEAN_LITERAL);
    createEAttribute(booleanLiteralEClass, BOOLEAN_LITERAL__VALUE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    floatEClass.getESuperTypes().add(this.getinitVals());
    logicalExpressionEClass.getESuperTypes().add(this.getExpression());
    equalityExpressionEClass.getESuperTypes().add(this.getExpression());
    relationalExpressionEClass.getESuperTypes().add(this.getExpression());
    sumOperationEClass.getESuperTypes().add(this.getExpression());
    minusOperationEClass.getESuperTypes().add(this.getExpression());
    termEClass.getESuperTypes().add(this.getExpression());
    negationExpressionEClass.getESuperTypes().add(this.getExpression());
    variableRefEClass.getESuperTypes().add(this.getExpression());
    integerLiteralEClass.getESuperTypes().add(this.getExpression());
    realLiteralEClass.getESuperTypes().add(this.getExpression());
    stringLiteralEClass.getESuperTypes().add(this.getExpression());
    booleanLiteralEClass.getESuperTypes().add(this.getExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(stochasticModelingEClass, StochasticModeling.class, "StochasticModeling", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStochasticModeling_StochasticModelElements(), this.getModelElementsDecaration(), null, "StochasticModelElements", null, 0, -1, StochasticModeling.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelElementsDecarationEClass, ModelElementsDecaration.class, "ModelElementsDecaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModelElementsDecaration_AbstractArchModel(), this.getAbsArchDecl(), null, "AbstractArchModel", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementsDecaration_ConstiuenetSystemSDesign(), this.getCSDecl(), null, "ConstiuenetSystemSDesign", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementsDecaration_MediatorDesign(), this.getMedDecl(), null, "MediatorDesign", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementsDecaration_ConcurrentConstraints(), this.getCConsDecl(), null, "ConcurrentConstraints", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementsDecaration_ArchitecutreElementsBehaviors(), this.getAElementsBehaviorRoutines(), null, "ArchitecutreElementsBehaviors", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getModelElementsDecaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementsDecaration_Interfce(), this.getpublicinterfaeceDef(), null, "Interfce", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModelElementsDecaration_ArchTraits(), this.gettraitDeclaration(), null, "ArchTraits", null, 0, -1, ModelElementsDecaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(csDeclEClass, CSDecl.class, "CSDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCSDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, CSDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCSDecl_CSDesignConsists(), this.getCSMembersDefintion(), null, "CSDesignConsists", null, 0, -1, CSDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(csMembersDefintionEClass, CSMembersDefintion.class, "CSMembersDefintion", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCSMembersDefintion_Ports(), this.getProtDeclaration(), null, "Ports", null, 0, -1, CSMembersDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCSMembersDefintion_AActions(), this.getAElementsBehaviorRoutines(), null, "AActions", null, 0, -1, CSMembersDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCSMembersDefintion_CSConConstraints(), this.getCConsDecl(), null, "CSConConstraints", null, 0, -1, CSMembersDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCSMembersDefintion_CSCoreBehavior(), this.getStochsticBehaviors(), null, "CSCoreBehavior", null, 0, -1, CSMembersDefintion.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stochsticBehaviorsEClass, StochsticBehaviors.class, "StochsticBehaviors", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStochsticBehaviors_Type(), ecorePackage.getEString(), "type", null, 0, 1, StochsticBehaviors.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStochsticBehaviors_Name(), ecorePackage.getEString(), "name", null, 0, 1, StochsticBehaviors.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStochsticBehaviors_ParamsDecl(), this.getformalParameters(), null, "paramsDecl", null, 0, 1, StochsticBehaviors.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStochsticBehaviors_Functions(), this.getAElementsBehaviorRoutines(), null, "functions", null, 0, -1, StochsticBehaviors.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(publicinterfaeceDefEClass, publicinterfaeceDef.class, "publicinterfaeceDef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getpublicinterfaeceDef_Name(), ecorePackage.getEString(), "Name", null, 0, 1, publicinterfaeceDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getpublicinterfaeceDef_ParamsDecl(), this.getformalParameters(), null, "paramsDecl", null, 0, 1, publicinterfaeceDef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(formalParametersEClass, formalParameters.class, "formalParameters", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getformalParameters_ParamsDecl(), this.getformalParameterList(), null, "paramsDecl", null, 0, -1, formalParameters.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(formalParameterListEClass, formalParameterList.class, "formalParameterList", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getformalParameterList_ParamDecl(), this.getformalParameter(), null, "paramDecl", null, 0, 1, formalParameterList.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getformalParameterList_ParamsDecl(), this.getformalParameter(), null, "paramsDecl", null, 0, -1, formalParameterList.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(formalParameterEClass, formalParameter.class, "formalParameter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getformalParameter_Type(), ecorePackage.getEString(), "type", null, 0, 1, formalParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getformalParameter_Name(), this.getvariableDeclaratorId(), null, "name", null, 0, 1, formalParameter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variableDeclaratorIdEClass, variableDeclaratorId.class, "variableDeclaratorId", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getvariableDeclaratorId_Name(), ecorePackage.getEString(), "name", null, 0, 1, variableDeclaratorId.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(protDeclarationEClass, ProtDeclaration.class, "ProtDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getProtDeclaration_Porttype(), ecorePackage.getEString(), "porttype", null, 0, 1, ProtDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getProtDeclaration_PubliicIntractionpointare(), this.getpublicinterfaeceDef(), null, "PubliicIntractionpointare", null, 0, 1, ProtDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProtDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, ProtDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(aElementsBehaviorRoutinesEClass, AElementsBehaviorRoutines.class, "AElementsBehaviorRoutines", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAElementsBehaviorRoutines_CollaborativeActions(), this.getCColActions(), null, "CollaborativeActions", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_CaolitionBinding(), this.getattachCSs(), null, "CaolitionBinding", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_RemoveElements(), this.getdetachCSs(), null, "RemoveElements", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_ConnectElenents(), this.getBindElements(), null, "ConnectElenents", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_ControlDecisions(), this.getControlDecisions(), null, "ControlDecisions", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_ActionReates(), this.getExponentialRates(), null, "ActionReates", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_AddElements(), this.getAddAElements(), null, "AddElements", null, 0, -1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAElementsBehaviorRoutines_HSFtypes(), this.getExpression(), null, "HSFtypes", null, 0, 1, AElementsBehaviorRoutines.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cColActionsEClass, CColActions.class, "CColActions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCColActions_Name(), ecorePackage.getEString(), "name", null, 0, 1, CColActions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCColActions_Type(), ecorePackage.getEString(), "type", null, 0, -1, CColActions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCColActions_ParamsDecl(), this.getformalParameters(), null, "paramsDecl", null, 0, -1, CColActions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCColActions_MethodBody(), this.getfunctinality(), null, "methodBody", null, 0, -1, CColActions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(functinalityEClass, functinality.class, "functinality", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getfunctinality_Functions(), this.getAElementsBehaviorRoutines(), null, "functions", null, 0, -1, functinality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getfunctinality_Actions(), this.getfunctinality(), null, "Actions", null, 0, 1, functinality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getfunctinality_Target(), this.getExponentialRates(), null, "target", null, 0, 1, functinality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(addAElementsEClass, AddAElements.class, "AddAElements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAddAElements_Name(), ecorePackage.getEString(), "name", null, 0, 1, AddAElements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAddAElements_Type(), ecorePackage.getEString(), "type", null, 0, 1, AddAElements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(attachCSsEClass, attachCSs.class, "attachCSs", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getattachCSs_AttachParam1(), this.getExpression(), null, "attachParam1", null, 0, -1, attachCSs.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getattachCSs_AttachParam2(), this.getExpression(), null, "attachParam2", null, 0, -1, attachCSs.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(detachCSsEClass, detachCSs.class, "detachCSs", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getdetachCSs_DetachParam1(), this.getExpression(), null, "detachParam1", null, 0, -1, detachCSs.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getdetachCSs_DetachParam2(), this.getExpression(), null, "detachParam2", null, 0, -1, detachCSs.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(bindElementsEClass, BindElements.class, "BindElements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBindElements_BindParam1(), this.getExpression(), null, "bindParam1", null, 0, -1, BindElements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBindElements_BindParam2(), this.getExpression(), null, "bindParam2", null, 0, -1, BindElements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(controlDecisionsEClass, ControlDecisions.class, "ControlDecisions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getControlDecisions_ExpressionDecl(), this.getAElementsBehaviorRoutines(), null, "expressionDecl", null, 0, 1, ControlDecisions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getControlDecisions_StatementDecl1(), this.getAElementsBehaviorRoutines(), null, "statementDecl1", null, 0, -1, ControlDecisions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getControlDecisions_ExpressionOrDecl(), this.getAElementsBehaviorRoutines(), null, "expressionOrDecl", null, 0, -1, ControlDecisions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getControlDecisions_StatementDecl2(), this.getAElementsBehaviorRoutines(), null, "statementDecl2", null, 0, -1, ControlDecisions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exponentialRatesEClass, ExponentialRates.class, "ExponentialRates", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExponentialRates_DelayValue(), ecorePackage.getEInt(), "delayValue", null, 0, 1, ExponentialRates.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExponentialRates_ExponentialRates(), this.getExpression(), null, "ExponentialRates", null, 0, 1, ExponentialRates.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cConsDeclEClass, CConsDecl.class, "CConsDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCConsDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, CConsDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCConsDecl_Askconstraints(), this.getAskopeator(), null, "Askconstraints", null, 0, -1, CConsDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCConsDecl_Tellconstraints(), this.getTelloperator(), null, "Tellconstraints", null, 0, -1, CConsDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(telloperatorEClass, Telloperator.class, "Telloperator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTelloperator_ConstraintShareDate(), ecorePackage.getEString(), "ConstraintShareDate", null, 0, 1, Telloperator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTelloperator_Rate(), this.getExponentialRates(), null, "rate", null, 0, 1, Telloperator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(askopeatorEClass, Askopeator.class, "Askopeator", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAskopeator_ConstraintData(), ecorePackage.getEString(), "ConstraintData", null, 0, 1, Askopeator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAskopeator_Rate(), this.getExponentialRates(), null, "rate", null, 0, 1, Askopeator.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(traitDeclarationEClass, traitDeclaration.class, "traitDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(gettraitDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, traitDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(gettraitDeclaration_Ports(), this.getProtDeclaration(), null, "ports", null, 0, -1, traitDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(gettraitDeclaration_Roles(), this.getMedRoleDeclaration(), null, "roles", null, 0, -1, traitDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(medDeclEClass, MedDecl.class, "MedDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMedDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, MedDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMedDecl_MedRoles(), this.getMedRoleDeclaration(), null, "MedRoles", null, 0, -1, MedDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMedDecl_AActions(), this.getAElementsBehaviorRoutines(), null, "AActions", null, 0, -1, MedDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMedDecl_CSConConstraints(), this.getCConsDecl(), null, "CSConConstraints", null, 0, -1, MedDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMedDecl_MedCoreBehavior(), this.getStochsticBehaviors(), null, "MedCoreBehavior", null, 0, -1, MedDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(medRoleDeclarationEClass, MedRoleDeclaration.class, "MedRoleDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMedRoleDeclaration_MediationRoles(), this.getDefineMediationRoles(), null, "MediationRoles", null, 0, -1, MedRoleDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(defineMediationRolesEClass, DefineMediationRoles.class, "DefineMediationRoles", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefineMediationRoles_Type(), ecorePackage.getEString(), "type", null, 0, 1, DefineMediationRoles.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDefineMediationRoles_PubliicIntractionpointare(), this.getpublicinterfaeceDef(), null, "PubliicIntractionpointare", null, 0, -1, DefineMediationRoles.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDefineMediationRoles_Name(), ecorePackage.getEString(), "name", null, 0, 1, DefineMediationRoles.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(absArchDeclEClass, AbsArchDecl.class, "AbsArchDecl", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAbsArchDecl_Name(), ecorePackage.getEString(), "name", null, 0, 1, AbsArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAbsArchDecl_Mediators(), this.getMedDecl(), null, "Mediators", null, 0, -1, AbsArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAbsArchDecl_Constitients(), this.getCSDecl(), null, "Constitients", null, 0, -1, AbsArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAbsArchDecl_AbstractCoaltion(), this.getAElementsBehaviorRoutines(), null, "AbstractCoaltion", null, 0, -1, AbsArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAbsArchDecl_GlobalProps(), this.getGlobalProperties(), null, "GlobalProps", null, 0, -1, AbsArchDecl.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(globalPropertiesEClass, GlobalProperties.class, "GlobalProperties", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGlobalProperties_PropertyType(), ecorePackage.getEString(), "PropertyType", null, 0, 1, GlobalProperties.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGlobalProperties_Name(), ecorePackage.getEString(), "name", null, 0, 1, GlobalProperties.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGlobalProperties_Attrinit(), this.getinitVals(), null, "attrinit", null, 0, 1, GlobalProperties.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(initValsEClass, initVals.class, "initVals", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(floatEClass, org.xtext.sosModeling.archModeling.hSFDSL.FLOAT.class, "FLOAT", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFLOAT_Value(), ecorePackage.getEInt(), "value", null, 0, 1, org.xtext.sosModeling.archModeling.hSFDSL.FLOAT.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressionEClass, Expression.class, "Expression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(logicalExpressionEClass, LogicalExpression.class, "LogicalExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLogicalExpression_Left(), this.getExpression(), null, "left", null, 0, 1, LogicalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLogicalExpression_Op(), ecorePackage.getEString(), "op", null, 0, 1, LogicalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getLogicalExpression_Right(), this.getExpression(), null, "right", null, 0, 1, LogicalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(equalityExpressionEClass, EqualityExpression.class, "EqualityExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEqualityExpression_Left(), this.getExpression(), null, "left", null, 0, 1, EqualityExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEqualityExpression_Op(), ecorePackage.getEString(), "op", null, 0, 1, EqualityExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEqualityExpression_Right(), this.getExpression(), null, "right", null, 0, 1, EqualityExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(relationalExpressionEClass, RelationalExpression.class, "RelationalExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRelationalExpression_Left(), this.getExpression(), null, "left", null, 0, 1, RelationalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRelationalExpression_Op(), ecorePackage.getEString(), "op", null, 0, 1, RelationalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelationalExpression_Right(), this.getExpression(), null, "right", null, 0, 1, RelationalExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sumOperationEClass, SumOperation.class, "SumOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSumOperation_Left(), this.getExpression(), null, "left", null, 0, 1, SumOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSumOperation_Op(), ecorePackage.getEString(), "op", null, 0, 1, SumOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSumOperation_Right(), this.getExpression(), null, "right", null, 0, 1, SumOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(minusOperationEClass, MinusOperation.class, "MinusOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMinusOperation_Left(), this.getExpression(), null, "left", null, 0, 1, MinusOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMinusOperation_Op(), ecorePackage.getEString(), "op", null, 0, 1, MinusOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMinusOperation_Right(), this.getExpression(), null, "right", null, 0, 1, MinusOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(termEClass, Term.class, "Term", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTerm_Left(), this.getExpression(), null, "left", null, 0, 1, Term.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTerm_Op(), ecorePackage.getEString(), "op", null, 0, 1, Term.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTerm_Right(), this.getExpression(), null, "right", null, 0, 1, Term.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(negationExpressionEClass, NegationExpression.class, "NegationExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNegationExpression_Expression(), this.getExpression(), null, "expression", null, 0, 1, NegationExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variableRefEClass, VariableRef.class, "VariableRef", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVariableRef_Variable(), ecorePackage.getEString(), "variable", null, 0, 1, VariableRef.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integerLiteralEClass, IntegerLiteral.class, "IntegerLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntegerLiteral_Value(), ecorePackage.getEInt(), "value", null, 0, 1, IntegerLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(realLiteralEClass, RealLiteral.class, "RealLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRealLiteral_Value(), this.getFLOAT(), null, "value", null, 0, 1, RealLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stringLiteralEClass, StringLiteral.class, "StringLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringLiteral_Value(), ecorePackage.getEString(), "value", null, 0, 1, StringLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(booleanLiteralEClass, BooleanLiteral.class, "BooleanLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBooleanLiteral_Value(), ecorePackage.getEString(), "value", null, 0, 1, BooleanLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //HSFDSLPackageImpl
