/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.sosModeling.archModeling.hSFDSL.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HSFDSLFactoryImpl extends EFactoryImpl implements HSFDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static HSFDSLFactory init()
  {
    try
    {
      HSFDSLFactory theHSFDSLFactory = (HSFDSLFactory)EPackage.Registry.INSTANCE.getEFactory(HSFDSLPackage.eNS_URI);
      if (theHSFDSLFactory != null)
      {
        return theHSFDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new HSFDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HSFDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case HSFDSLPackage.STOCHASTIC_MODELING: return createStochasticModeling();
      case HSFDSLPackage.MODEL_ELEMENTS_DECARATION: return createModelElementsDecaration();
      case HSFDSLPackage.CS_DECL: return createCSDecl();
      case HSFDSLPackage.CS_MEMBERS_DEFINTION: return createCSMembersDefintion();
      case HSFDSLPackage.STOCHSTIC_BEHAVIORS: return createStochsticBehaviors();
      case HSFDSLPackage.PUBLICINTERFAECE_DEF: return createpublicinterfaeceDef();
      case HSFDSLPackage.FORMAL_PARAMETERS: return createformalParameters();
      case HSFDSLPackage.FORMAL_PARAMETER_LIST: return createformalParameterList();
      case HSFDSLPackage.FORMAL_PARAMETER: return createformalParameter();
      case HSFDSLPackage.VARIABLE_DECLARATOR_ID: return createvariableDeclaratorId();
      case HSFDSLPackage.PROT_DECLARATION: return createProtDeclaration();
      case HSFDSLPackage.AELEMENTS_BEHAVIOR_ROUTINES: return createAElementsBehaviorRoutines();
      case HSFDSLPackage.CCOL_ACTIONS: return createCColActions();
      case HSFDSLPackage.FUNCTINALITY: return createfunctinality();
      case HSFDSLPackage.ADD_AELEMENTS: return createAddAElements();
      case HSFDSLPackage.ATTACH_CSS: return createattachCSs();
      case HSFDSLPackage.DETACH_CSS: return createdetachCSs();
      case HSFDSLPackage.BIND_ELEMENTS: return createBindElements();
      case HSFDSLPackage.CONTROL_DECISIONS: return createControlDecisions();
      case HSFDSLPackage.EXPONENTIAL_RATES: return createExponentialRates();
      case HSFDSLPackage.CCONS_DECL: return createCConsDecl();
      case HSFDSLPackage.TELLOPERATOR: return createTelloperator();
      case HSFDSLPackage.ASKOPEATOR: return createAskopeator();
      case HSFDSLPackage.TRAIT_DECLARATION: return createtraitDeclaration();
      case HSFDSLPackage.MED_DECL: return createMedDecl();
      case HSFDSLPackage.MED_ROLE_DECLARATION: return createMedRoleDeclaration();
      case HSFDSLPackage.DEFINE_MEDIATION_ROLES: return createDefineMediationRoles();
      case HSFDSLPackage.ABS_ARCH_DECL: return createAbsArchDecl();
      case HSFDSLPackage.GLOBAL_PROPERTIES: return createGlobalProperties();
      case HSFDSLPackage.INIT_VALS: return createinitVals();
      case HSFDSLPackage.FLOAT: return createFLOAT();
      case HSFDSLPackage.EXPRESSION: return createExpression();
      case HSFDSLPackage.LOGICAL_EXPRESSION: return createLogicalExpression();
      case HSFDSLPackage.EQUALITY_EXPRESSION: return createEqualityExpression();
      case HSFDSLPackage.RELATIONAL_EXPRESSION: return createRelationalExpression();
      case HSFDSLPackage.SUM_OPERATION: return createSumOperation();
      case HSFDSLPackage.MINUS_OPERATION: return createMinusOperation();
      case HSFDSLPackage.TERM: return createTerm();
      case HSFDSLPackage.NEGATION_EXPRESSION: return createNegationExpression();
      case HSFDSLPackage.VARIABLE_REF: return createVariableRef();
      case HSFDSLPackage.INTEGER_LITERAL: return createIntegerLiteral();
      case HSFDSLPackage.REAL_LITERAL: return createRealLiteral();
      case HSFDSLPackage.STRING_LITERAL: return createStringLiteral();
      case HSFDSLPackage.BOOLEAN_LITERAL: return createBooleanLiteral();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StochasticModeling createStochasticModeling()
  {
    StochasticModelingImpl stochasticModeling = new StochasticModelingImpl();
    return stochasticModeling;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ModelElementsDecaration createModelElementsDecaration()
  {
    ModelElementsDecarationImpl modelElementsDecaration = new ModelElementsDecarationImpl();
    return modelElementsDecaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CSDecl createCSDecl()
  {
    CSDeclImpl csDecl = new CSDeclImpl();
    return csDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CSMembersDefintion createCSMembersDefintion()
  {
    CSMembersDefintionImpl csMembersDefintion = new CSMembersDefintionImpl();
    return csMembersDefintion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StochsticBehaviors createStochsticBehaviors()
  {
    StochsticBehaviorsImpl stochsticBehaviors = new StochsticBehaviorsImpl();
    return stochsticBehaviors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public publicinterfaeceDef createpublicinterfaeceDef()
  {
    publicinterfaeceDefImpl publicinterfaeceDef = new publicinterfaeceDefImpl();
    return publicinterfaeceDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public formalParameters createformalParameters()
  {
    formalParametersImpl formalParameters = new formalParametersImpl();
    return formalParameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public formalParameterList createformalParameterList()
  {
    formalParameterListImpl formalParameterList = new formalParameterListImpl();
    return formalParameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public formalParameter createformalParameter()
  {
    formalParameterImpl formalParameter = new formalParameterImpl();
    return formalParameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public variableDeclaratorId createvariableDeclaratorId()
  {
    variableDeclaratorIdImpl variableDeclaratorId = new variableDeclaratorIdImpl();
    return variableDeclaratorId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProtDeclaration createProtDeclaration()
  {
    ProtDeclarationImpl protDeclaration = new ProtDeclarationImpl();
    return protDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AElementsBehaviorRoutines createAElementsBehaviorRoutines()
  {
    AElementsBehaviorRoutinesImpl aElementsBehaviorRoutines = new AElementsBehaviorRoutinesImpl();
    return aElementsBehaviorRoutines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CColActions createCColActions()
  {
    CColActionsImpl cColActions = new CColActionsImpl();
    return cColActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public functinality createfunctinality()
  {
    functinalityImpl functinality = new functinalityImpl();
    return functinality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddAElements createAddAElements()
  {
    AddAElementsImpl addAElements = new AddAElementsImpl();
    return addAElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public attachCSs createattachCSs()
  {
    attachCSsImpl attachCSs = new attachCSsImpl();
    return attachCSs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public detachCSs createdetachCSs()
  {
    detachCSsImpl detachCSs = new detachCSsImpl();
    return detachCSs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BindElements createBindElements()
  {
    BindElementsImpl bindElements = new BindElementsImpl();
    return bindElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ControlDecisions createControlDecisions()
  {
    ControlDecisionsImpl controlDecisions = new ControlDecisionsImpl();
    return controlDecisions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExponentialRates createExponentialRates()
  {
    ExponentialRatesImpl exponentialRates = new ExponentialRatesImpl();
    return exponentialRates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CConsDecl createCConsDecl()
  {
    CConsDeclImpl cConsDecl = new CConsDeclImpl();
    return cConsDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Telloperator createTelloperator()
  {
    TelloperatorImpl telloperator = new TelloperatorImpl();
    return telloperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Askopeator createAskopeator()
  {
    AskopeatorImpl askopeator = new AskopeatorImpl();
    return askopeator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public traitDeclaration createtraitDeclaration()
  {
    traitDeclarationImpl traitDeclaration = new traitDeclarationImpl();
    return traitDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MedDecl createMedDecl()
  {
    MedDeclImpl medDecl = new MedDeclImpl();
    return medDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MedRoleDeclaration createMedRoleDeclaration()
  {
    MedRoleDeclarationImpl medRoleDeclaration = new MedRoleDeclarationImpl();
    return medRoleDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DefineMediationRoles createDefineMediationRoles()
  {
    DefineMediationRolesImpl defineMediationRoles = new DefineMediationRolesImpl();
    return defineMediationRoles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbsArchDecl createAbsArchDecl()
  {
    AbsArchDeclImpl absArchDecl = new AbsArchDeclImpl();
    return absArchDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GlobalProperties createGlobalProperties()
  {
    GlobalPropertiesImpl globalProperties = new GlobalPropertiesImpl();
    return globalProperties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public initVals createinitVals()
  {
    initValsImpl initVals = new initValsImpl();
    return initVals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FLOAT createFLOAT()
  {
    FLOATImpl float_ = new FLOATImpl();
    return float_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LogicalExpression createLogicalExpression()
  {
    LogicalExpressionImpl logicalExpression = new LogicalExpressionImpl();
    return logicalExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EqualityExpression createEqualityExpression()
  {
    EqualityExpressionImpl equalityExpression = new EqualityExpressionImpl();
    return equalityExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationalExpression createRelationalExpression()
  {
    RelationalExpressionImpl relationalExpression = new RelationalExpressionImpl();
    return relationalExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SumOperation createSumOperation()
  {
    SumOperationImpl sumOperation = new SumOperationImpl();
    return sumOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MinusOperation createMinusOperation()
  {
    MinusOperationImpl minusOperation = new MinusOperationImpl();
    return minusOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Term createTerm()
  {
    TermImpl term = new TermImpl();
    return term;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NegationExpression createNegationExpression()
  {
    NegationExpressionImpl negationExpression = new NegationExpressionImpl();
    return negationExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableRef createVariableRef()
  {
    VariableRefImpl variableRef = new VariableRefImpl();
    return variableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegerLiteral createIntegerLiteral()
  {
    IntegerLiteralImpl integerLiteral = new IntegerLiteralImpl();
    return integerLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RealLiteral createRealLiteral()
  {
    RealLiteralImpl realLiteral = new RealLiteralImpl();
    return realLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringLiteral createStringLiteral()
  {
    StringLiteralImpl stringLiteral = new StringLiteralImpl();
    return stringLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanLiteral createBooleanLiteral()
  {
    BooleanLiteralImpl booleanLiteral = new BooleanLiteralImpl();
    return booleanLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HSFDSLPackage getHSFDSLPackage()
  {
    return (HSFDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static HSFDSLPackage getPackage()
  {
    return HSFDSLPackage.eINSTANCE;
  }

} //HSFDSLFactoryImpl
