/*
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.sosModeling.archModeling.parser.antlr.internal.InternalSFDSLParser;
import org.xtext.sosModeling.archModeling.services.SFDSLGrammarAccess;

public class SFDSLParser extends AbstractAntlrParser {

	@Inject
	private SFDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSFDSLParser createParser(XtextTokenStream stream) {
		return new InternalSFDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "StochasticModeling";
	}

	public SFDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SFDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
