/**
 * generated by Xtext 2.19.0
 */
package org.xtext.hybridStochastic.ide;

import org.xtext.hybridStochastic.ide.AbstractHSFMSoSIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class HSFMSoSIdeModule extends AbstractHSFMSoSIdeModule {
}
