/**
 * generated by Xtext 2.19.0
 */
package org.xtext.hybridStochastic.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HSFMSoSIdeSetup /* implements HSFMSoSStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nHSFMSoSRuntimeModule cannot be resolved.");
  }
}
