/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>attach CSs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.attachCSs#getAttachParam1 <em>Attach Param1</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.attachCSs#getAttachParam2 <em>Attach Param2</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getattachCSs()
 * @model
 * @generated
 */
public interface attachCSs extends EObject
{
  /**
   * Returns the value of the '<em><b>Attach Param1</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attach Param1</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getattachCSs_AttachParam1()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getAttachParam1();

  /**
   * Returns the value of the '<em><b>Attach Param2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attach Param2</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getattachCSs_AttachParam2()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getAttachParam2();

} // attachCSs
