/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bind Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.BindElements#getBindParam1 <em>Bind Param1</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.BindElements#getBindParam2 <em>Bind Param2</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getBindElements()
 * @model
 * @generated
 */
public interface BindElements extends EObject
{
  /**
   * Returns the value of the '<em><b>Bind Param1</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bind Param1</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getBindElements_BindParam1()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getBindParam1();

  /**
   * Returns the value of the '<em><b>Bind Param2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bind Param2</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getBindElements_BindParam2()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getBindParam2();

} // BindElements
