/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CS Members Defintion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.CSMembersDefintion#getPorts <em>Ports</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.CSMembersDefintion#getAActions <em>AActions</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.CSMembersDefintion#getCSConConstraints <em>CS Con Constraints</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.CSMembersDefintion#getCSCoreBehavior <em>CS Core Behavior</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getCSMembersDefintion()
 * @model
 * @generated
 */
public interface CSMembersDefintion extends EObject
{
  /**
   * Returns the value of the '<em><b>Ports</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.ProtDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getCSMembersDefintion_Ports()
   * @model containment="true"
   * @generated
   */
  EList<ProtDeclaration> getPorts();

  /**
   * Returns the value of the '<em><b>AActions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.AElementsBehaviorRoutines}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>AActions</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getCSMembersDefintion_AActions()
   * @model containment="true"
   * @generated
   */
  EList<AElementsBehaviorRoutines> getAActions();

  /**
   * Returns the value of the '<em><b>CS Con Constraints</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.CConsDecl}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CS Con Constraints</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getCSMembersDefintion_CSConConstraints()
   * @model containment="true"
   * @generated
   */
  EList<CConsDecl> getCSConConstraints();

  /**
   * Returns the value of the '<em><b>CS Core Behavior</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.StochsticBehaviors}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CS Core Behavior</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getCSMembersDefintion_CSCoreBehavior()
   * @model containment="true"
   * @generated
   */
  EList<StochsticBehaviors> getCSCoreBehavior();

} // CSMembersDefintion
