/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>formal Parameter List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.formalParameterList#getParamDecl <em>Param Decl</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.formalParameterList#getParamsDecl <em>Params Decl</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getformalParameterList()
 * @model
 * @generated
 */
public interface formalParameterList extends EObject
{
  /**
   * Returns the value of the '<em><b>Param Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Decl</em>' containment reference.
   * @see #setParamDecl(formalParameter)
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getformalParameterList_ParamDecl()
   * @model containment="true"
   * @generated
   */
  formalParameter getParamDecl();

  /**
   * Sets the value of the '{@link org.xtext.sosModeling.archModeling.hSFDSL.formalParameterList#getParamDecl <em>Param Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Decl</em>' containment reference.
   * @see #getParamDecl()
   * @generated
   */
  void setParamDecl(formalParameter value);

  /**
   * Returns the value of the '<em><b>Params Decl</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.formalParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params Decl</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getformalParameterList_ParamsDecl()
   * @model containment="true"
   * @generated
   */
  EList<formalParameter> getParamsDecl();

} // formalParameterList
