/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>functinality</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.functinality#getFunctions <em>Functions</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.functinality#getActions <em>Actions</em>}</li>
 *   <li>{@link org.xtext.sosModeling.archModeling.hSFDSL.functinality#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getfunctinality()
 * @model
 * @generated
 */
public interface functinality extends EObject
{
  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sosModeling.archModeling.hSFDSL.AElementsBehaviorRoutines}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getfunctinality_Functions()
   * @model containment="true"
   * @generated
   */
  EList<AElementsBehaviorRoutines> getFunctions();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' reference.
   * @see #setActions(functinality)
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getfunctinality_Actions()
   * @model
   * @generated
   */
  functinality getActions();

  /**
   * Sets the value of the '{@link org.xtext.sosModeling.archModeling.hSFDSL.functinality#getActions <em>Actions</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actions</em>' reference.
   * @see #getActions()
   * @generated
   */
  void setActions(functinality value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(ExponentialRates)
   * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getfunctinality_Target()
   * @model
   * @generated
   */
  ExponentialRates getTarget();

  /**
   * Sets the value of the '{@link org.xtext.sosModeling.archModeling.hSFDSL.functinality#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(ExponentialRates value);

} // functinality
