/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage
 * @generated
 */
public interface HSFDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HSFDSLFactory eINSTANCE = org.xtext.sosModeling.archModeling.hSFDSL.impl.HSFDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Stochastic Modeling</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochastic Modeling</em>'.
   * @generated
   */
  StochasticModeling createStochasticModeling();

  /**
   * Returns a new object of class '<em>Model Elements Decaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model Elements Decaration</em>'.
   * @generated
   */
  ModelElementsDecaration createModelElementsDecaration();

  /**
   * Returns a new object of class '<em>CS Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CS Decl</em>'.
   * @generated
   */
  CSDecl createCSDecl();

  /**
   * Returns a new object of class '<em>CS Members Defintion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CS Members Defintion</em>'.
   * @generated
   */
  CSMembersDefintion createCSMembersDefintion();

  /**
   * Returns a new object of class '<em>Stochstic Behaviors</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochstic Behaviors</em>'.
   * @generated
   */
  StochsticBehaviors createStochsticBehaviors();

  /**
   * Returns a new object of class '<em>publicinterfaece Def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>publicinterfaece Def</em>'.
   * @generated
   */
  publicinterfaeceDef createpublicinterfaeceDef();

  /**
   * Returns a new object of class '<em>formal Parameters</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>formal Parameters</em>'.
   * @generated
   */
  formalParameters createformalParameters();

  /**
   * Returns a new object of class '<em>formal Parameter List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>formal Parameter List</em>'.
   * @generated
   */
  formalParameterList createformalParameterList();

  /**
   * Returns a new object of class '<em>formal Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>formal Parameter</em>'.
   * @generated
   */
  formalParameter createformalParameter();

  /**
   * Returns a new object of class '<em>variable Declarator Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>variable Declarator Id</em>'.
   * @generated
   */
  variableDeclaratorId createvariableDeclaratorId();

  /**
   * Returns a new object of class '<em>Prot Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Prot Declaration</em>'.
   * @generated
   */
  ProtDeclaration createProtDeclaration();

  /**
   * Returns a new object of class '<em>AElements Behavior Routines</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AElements Behavior Routines</em>'.
   * @generated
   */
  AElementsBehaviorRoutines createAElementsBehaviorRoutines();

  /**
   * Returns a new object of class '<em>CCol Actions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCol Actions</em>'.
   * @generated
   */
  CColActions createCColActions();

  /**
   * Returns a new object of class '<em>functinality</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>functinality</em>'.
   * @generated
   */
  functinality createfunctinality();

  /**
   * Returns a new object of class '<em>Add AElements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add AElements</em>'.
   * @generated
   */
  AddAElements createAddAElements();

  /**
   * Returns a new object of class '<em>attach CSs</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>attach CSs</em>'.
   * @generated
   */
  attachCSs createattachCSs();

  /**
   * Returns a new object of class '<em>detach CSs</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>detach CSs</em>'.
   * @generated
   */
  detachCSs createdetachCSs();

  /**
   * Returns a new object of class '<em>Bind Elements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bind Elements</em>'.
   * @generated
   */
  BindElements createBindElements();

  /**
   * Returns a new object of class '<em>Control Decisions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Control Decisions</em>'.
   * @generated
   */
  ControlDecisions createControlDecisions();

  /**
   * Returns a new object of class '<em>Exponential Rates</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exponential Rates</em>'.
   * @generated
   */
  ExponentialRates createExponentialRates();

  /**
   * Returns a new object of class '<em>CCons Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CCons Decl</em>'.
   * @generated
   */
  CConsDecl createCConsDecl();

  /**
   * Returns a new object of class '<em>Telloperator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Telloperator</em>'.
   * @generated
   */
  Telloperator createTelloperator();

  /**
   * Returns a new object of class '<em>Askopeator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Askopeator</em>'.
   * @generated
   */
  Askopeator createAskopeator();

  /**
   * Returns a new object of class '<em>trait Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>trait Declaration</em>'.
   * @generated
   */
  traitDeclaration createtraitDeclaration();

  /**
   * Returns a new object of class '<em>Med Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Med Decl</em>'.
   * @generated
   */
  MedDecl createMedDecl();

  /**
   * Returns a new object of class '<em>Med Role Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Med Role Declaration</em>'.
   * @generated
   */
  MedRoleDeclaration createMedRoleDeclaration();

  /**
   * Returns a new object of class '<em>Define Mediation Roles</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Define Mediation Roles</em>'.
   * @generated
   */
  DefineMediationRoles createDefineMediationRoles();

  /**
   * Returns a new object of class '<em>Abs Arch Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abs Arch Decl</em>'.
   * @generated
   */
  AbsArchDecl createAbsArchDecl();

  /**
   * Returns a new object of class '<em>Global Properties</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Global Properties</em>'.
   * @generated
   */
  GlobalProperties createGlobalProperties();

  /**
   * Returns a new object of class '<em>init Vals</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>init Vals</em>'.
   * @generated
   */
  initVals createinitVals();

  /**
   * Returns a new object of class '<em>FLOAT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>FLOAT</em>'.
   * @generated
   */
  FLOAT createFLOAT();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Logical Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logical Expression</em>'.
   * @generated
   */
  LogicalExpression createLogicalExpression();

  /**
   * Returns a new object of class '<em>Equality Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equality Expression</em>'.
   * @generated
   */
  EqualityExpression createEqualityExpression();

  /**
   * Returns a new object of class '<em>Relational Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relational Expression</em>'.
   * @generated
   */
  RelationalExpression createRelationalExpression();

  /**
   * Returns a new object of class '<em>Sum Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sum Operation</em>'.
   * @generated
   */
  SumOperation createSumOperation();

  /**
   * Returns a new object of class '<em>Minus Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Minus Operation</em>'.
   * @generated
   */
  MinusOperation createMinusOperation();

  /**
   * Returns a new object of class '<em>Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Term</em>'.
   * @generated
   */
  Term createTerm();

  /**
   * Returns a new object of class '<em>Negation Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Negation Expression</em>'.
   * @generated
   */
  NegationExpression createNegationExpression();

  /**
   * Returns a new object of class '<em>Variable Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Ref</em>'.
   * @generated
   */
  VariableRef createVariableRef();

  /**
   * Returns a new object of class '<em>Integer Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integer Literal</em>'.
   * @generated
   */
  IntegerLiteral createIntegerLiteral();

  /**
   * Returns a new object of class '<em>Real Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Real Literal</em>'.
   * @generated
   */
  RealLiteral createRealLiteral();

  /**
   * Returns a new object of class '<em>String Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Literal</em>'.
   * @generated
   */
  StringLiteral createStringLiteral();

  /**
   * Returns a new object of class '<em>Boolean Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Literal</em>'.
   * @generated
   */
  BooleanLiteral createBooleanLiteral();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  HSFDSLPackage getHSFDSLPackage();

} //HSFDSLFactory
