/**
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.hSFDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>init Vals</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sosModeling.archModeling.hSFDSL.HSFDSLPackage#getinitVals()
 * @model
 * @generated
 */
public interface initVals extends EObject
{
} // initVals
