/*
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.SoSModeling.HSFDSL.ui.internal.HSFDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SFDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HSFDSLActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HSFDSLActivator activator = HSFDSLActivator.getInstance();
		return activator != null ? activator.getInjector(HSFDSLActivator.ORG_XTEXT_SOSMODELING_ARCHMODELING_SFDSL) : null;
	}

}
