/*
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSFDSLScopeProvider extends DelegatingScopeProvider {
}
