/*
 * generated by Xtext 2.19.0
 */
package org.xtext.sosModeling.archModeling.ide


/**
 * Use this class to register ide components.
 */
class SFDSLIdeModule extends AbstractSFDSLIdeModule {
}
